### ISSUE TITLE
Encoder not working

### ISSUE THREAD

**Issue by zauklian** [WWBN/AVideo-Encoder#206]
I'm installed AVideo and AVideo-Encoder on Debian 9, PHP 7.2.26 and MySQL 5.5.46.
While uploading video the encoding is never completed.

07-Jan-2020 10:38:53 Asia/Singapore] Upload.php will set format
[07-Jan-2020 10:38:53 Asia/Singapore] Upload.php will let function decide decideFormatOrder
[07-Jan-2020 10:38:53 Asia/Singapore] decideFormatOrder: {"file":"Test.mp4","audioOnly":"false","spectrum":"false","webm":"false","inputHLS":"false","inputLow":"true","inputSD":"true","inputHD":"true","title":"Test","description":"","categories_id":"0"}
[07-Jan-2020 10:38:53 Asia/Singapore] decideFormatOrder: MP4 All
[07-Jan-2020 10:38:53 Asia/Singapore] Encoder::sendFile videos_id=0, format=mp4
[07-Jan-2020 10:38:53 Asia/Singapore] {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}
[07-Jan-2020 10:38:53 Asia/Singapore] Encoder::sendFile sending file to http://localhost/aVideoEncoder.json
[07-Jan-2020 10:38:53 Asia/Singapore] Encoder::sendFile reading file from 
[07-Jan-2020 10:38:54 Asia/Singapore] AVideo-Streamer answer {"error":false,"video_id":38}
[07-Jan-2020 10:38:54 Asia/Singapore] {"error":false,"format":"mp4","file":"","resolution":"","videoDownloadedLink":null,"target":"http:\/\/localhost\/aVideoEncoder.json","postFields":11,"response_raw":"{\"error\":false,\"video_id\":38}","response":{"error":false,"video_id":38}}
[07-Jan-2020 10:38:54 Asia/Singapore] Encoder::save id=() title=(Test)[{"file":"\/var\/www\/AVideo\/Encoder\/objects\/Encoder.php","line":143,"function":"save","class":"Encoder","object":{},"type":"->","args":[]},{"file":"\/var\/www\/AVideo\/Encoder\/objects\/Encoder.php","line":850,"function":"setReturn_varsVideos_id","class":"Encoder","object":{},"type":"->","args":[38]},{"file":"\/var\/www\/AVideo\/Encoder\/view\/upload.php","line":89,"function":"sendFile","class":"Encoder","type":"::","args":["",0,"mp4",{}]},{"file":"\/var\/www\/AVideo\/Encoder\/view\/jquery-file-upload\/server\/php\/fileuploadchunkdone.php","line":30,"args":["\/var\/www\/AVideo\/Encoder\/view\/upload.php"],"function":"require_once"}]
[07-Jan-2020 10:38:54 Asia/Singapore] Encoder::save id=(7) title=(Test)[{"file":"\/var\/www\/AVideo\/Encoder\/view\/upload.php","line":96,"function":"save","class":"Encoder","object":{},"type":"->","args":[]},{"file":"\/var\/www\/AVideo\/Encoder\/view\/jquery-file-upload\/server\/php\/fileuploadchunkdone.php","line":30,"args":["\/var\/www\/AVideo\/Encoder\/view\/upload.php"],"function":"require_once"}]
[07-Jan-2020 10:38:55 Asia/Singapore] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/AVideo/Encoder/objects/include_config.php:16
Stack trace:
#0 /var/www/AVideo/Encoder/videos/configuration.php(19): require_once()
#1 /var/www/AVideo/Encoder/view/run.php(3): require_once('/var/www/AVideo...')
#2 {main}
  thrown in /var/www/AVideo/Encoder/objects/include_config.php on line 16
[07-Jan-2020 10:38:56 Asia/Singapore] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/AVideo/Encoder/objects/include_config.php:16
Stack trace:
#0 /var/www/AVideo/Encoder/videos/configuration.php(19): require_once()
#1 /var/www/AVideo/Encoder/view/run.php(3): require_once('/var/www/AVideo...')
#2 {main}
  thrown in /var/www/AVideo/Encoder/objects/include_config.php on line 16
[07-Jan-2020 10:39:00 Asia/Singapore] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/AVideo/Encoder/objects/include_config.php:16
Stack trace:
#0 /var/www/AVideo/Encoder/videos/configuration.php(19): require_once()
#1 /var/www/AVideo/Encoder/view/run.php(3): require_once('/var/www/AVideo...')
#2 {main}
  thrown in /var/www/AVideo/Encoder/objects/include_config.php on line 16
[07-Jan-2020 10:39:01 Asia/Singapore] PHP Fatal error:  Uncaught Error: Class 'mysqli' not found in /var/www/AVideo/Encoder/objects/include_config.php:16
Stack trace:
#0 /var/www/AVideo/Encoder/videos/configuration.php(19): require_once()
#1 /var/www/AVideo/Encoder/view/run.php(3): require_once('/var/www/AVideo...')
#2 {main}
  thrown in /var/www/AVideo/Encoder/objects/include_config.php on line 16

**Comment by akhilleusuggo** [comment]
> PHP Fatal error: Uncaught Error: Class 'mysqli' not found

This means you don't have mysqli installed . 
I don't know about Debian 9 , but ubuntu 18.04 `apt-get install php7.2-mysql`

**Comment by zauklian** [comment]
> 
> 
> > PHP Fatal error: Uncaught Error: Class 'mysqli' not found
> 
> This means you don't have mysqli installed .
> I don't know about Debian 9 , but ubuntu 18.04 `apt-get install php7.2-mysql`

I have installed mysqli.
![mysqli](https://user-images.githubusercontent.com/538670/71865038-91139580-313c-11ea-96dc-f537affba764.png)

**Comment by zauklian** [comment]
> 
> 
> > PHP Fatal error: Uncaught Error: Class 'mysqli' not found
> 
> This means you don't have mysqli installed .
> I don't know about Debian 9 , but ubuntu 18.04 `apt-get install php7.2-mysql`

I install php7.3-mysql and then working fine.
Thank you for your support and help.
