### ISSUE TITLE
pip install --upgrade youtube-dl

### ISSUE THREAD

**Issue by Erreur1978** [WWBN/AVideo-Encoder#328]
Stored in directory: /root/.cache/pip/wheels/d9/3c/49/0725759c13b5dc65b58490b1a271b9b664912f1f43f0cfd769
Successfully built pip
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed pip-21.0.1
root@BoX2:/var/www# sudo pip install --upgrade youtube-dl
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax

**Comment by akhilleusuggo** [comment]
What Linux Distro are you using ? And what version ?

**Comment by Erreur1978** [comment]
Ubuntu 32bit 16.04

**Comment by akhilleusuggo** [comment]
It's an old version of ubuntu . Maybe you shouldn't have upgraded the pip .
Try installing pip3 ;

`sudo apt-get -y install python3-pip` , or rollback version .
I'm using pip3 personally .
