### ISSUE TITLE
/usr/bin/env: ‘python’: No such file or directory

### ISSUE THREAD

**Issue by maverickfilmes** [WWBN/AVideo-Encoder#513]
When clicking share, with a youtube link, I get the following title error

![Error](https://i.imgur.com/qQHJnHS.png)

**Comment by maverickfilmes** [comment]
I did the following commands and solved the problem above:

sudo ln -s /usr/bin/python3 /usr/bin/python

export PATH="/usr/bin:$PATH"

----------------------------------------------------------------------------------------------------------
But now this error appears:

WARNING: Writing cache to '/var/www/.cache/youtube-dl/youtube-sigfuncs/js_1dda5629_107.json' failed: Traceback (most recent call last):, File "/usr/local/bin/youtube-dl/youtube_dl/cache.py", line 49, in store, os.makedirs(os.path.dirname(fn)), File "/usr/lib/python3.10/os.py", line 215, in makedirs, makedirs(head, exist_ok=exist_ok), File "/usr/lib/python3.10/os.py", line 215, in makedirs, makedirs(head, exist_ok=exist_ok), File "/usr/lib/python3.10/os.py", line 225, in makedirs, mkdir(name, mode), PermissionError: [Errno 13] Permission denied: '/var/www/.cache', , WARNING: Writing cache to '/var/www/.cache/youtube-dl/youtube-sigfuncs/js_1dda5629_103.json' failed: Traceback (most recent call last):, File "/usr/local/bin/youtube-dl/youtube_dl/cache.py", line 49, in store, os.makedirs(os.path.dirname(fn)), File "/usr/lib/python3.10/os.py", line 215, in makedirs, makedirs(head, exist_ok=exist_ok), File "/usr/lib/python3.10/os.py", line 215, in makedirs, makedirs(head, exist_ok=exist_ok), File "/usr/lib/python3.10/os.py", line 225, in makedirs, mkdir(name, mode), PermissionError: [Errno 13] Permission denied: '/var/www/.cache', , ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by DanielnetoDotCom** [comment]
You may need to google to find out how to resolve your youtube-dl installation.

also I recommend you to install yt-dlp instead
