### ISSUE TITLE
File sits in sharing que and doesn't process.

### ISSUE THREAD

**Issue by RogerWaldrip** [WWBN/AVideo-Encoder#524]
Ubuntu 22.04
Apache2
PHP8.3 with extensions php8.3-mysql and php8.3-mysqli.
AVideo server works fine and shows no problems in the Administrative Health porrtion.

Encoder que log from web page shows "try [1] Error on return_vars->videos_id"

Encoder log file displays the following;
[24-Dec-2023 01:17:12 UTC] PHP Fatal error:  Uncaught Error: Class "mysqli" not found in /var/www/html/APACHE/DRIPCODER/objects/include_config.php:31
Stack trace:
#0 /var/www/html/APACHE/DRIPCODER/videos/configuration.php(37): require_once()
#1 /var/www/html/APACHE/DRIPCODER/view/run.php(4): require_once('...')
#2 {main}
  thrown in /var/www/html/APACHE/DRIPCODER/objects/include_config.php on line 31

then some stuff then shows;

[24-Dec-2023 01:18:47 UTC] PHP Fatal error:  Uncaught Error: Class "mysqli" not found in /var/www/html/APACHE/DRIPCODER/objects/include_config.php:31
Stack trace:
#0 /var/www/html/APACHE/DRIPCODER/videos/configuration.php(37): require_once()
#1 /var/www/html/APACHE/DRIPCODER/view/run.php(4): require_once('...')
#2 {main}
  thrown in /var/www/html/APACHE/DRIPCODER/objects/include_config.php on line 31
[24-Dec-2023 01:18:53 UTC] PHP Fatal error:  Uncaught Error: Class "mysqli" not found in /var/www/html/APACHE/DRIPCODER/objects/include_config.php:31
Stack trace:
#0 /var/www/html/APACHE/DRIPCODER/videos/configuration.php(37): require_once()
#1 /var/www/html/APACHE/DRIPCODER/view/run.php(4): require_once('...')
#2 {main}
  thrown in /var/www/html/APACHE/DRIPCODER/objects/include_config.php on line 31
[24-Dec-2023 01:19:00 UTC] PHP Fatal error:  Uncaught Error: Class "mysqli" not found in /var/www/html/APACHE/DRIPCODER/objects/include_config.php:31
Stack trace:
#0 /var/www/html/APACHE/DRIPCODER/videos/configuration.php(37): require_once()
#1 /var/www/html/APACHE/DRIPCODER/view/run.php(4): require_once('...')
#2 {main}
  thrown in /var/www/html/APACHE/DRIPCODER/objects/include_config.php on line 31
[24-Dec-2023 01:19:07 UTC] PHP Fatal error:  Uncaught Error: Class "mysqli" not found in /var/www/html/APACHE/DRIPCODER/objects/include_config.php:31
Stack trace:
#0 /var/www/html/APACHE/DRIPCODER/videos/configuration.php(37): require_once()
#1 /var/www/html/APACHE/DRIPCODER/view/run.php(4): require_once('...')
#2 {main}
  thrown in /var/www/html/APACHE/DRIPCODER/objects/include_config.php on line 31

**Comment by DanielnetoDotCom** [comment]
Google for this and make sure you installed it properly

`PHP Fatal error: Uncaught Error: Class "mysqli" not found `

also make sure you install it to your command line PHP version
