### ISSUE TITLE
PHP Fatal error:  Uncaught mysqli_sql_exception: MySQL server has gone away

### ISSUE THREAD

**Issue by s-maisch** [WWBN/AVideo-Encoder#525]
Hello,

i have reinstalled the site, and recovered the Database, the site are working , but the encoder ist greyed.

The Log says : 

```
[30-Dec-2023 01:33:22 UTC] PHP Fatal error:  Uncaught mysqli_sql_exception: MySQL server has gone away in /var/www/AVideo/upload/objects/Streamer.php:26
Stack trace:
#0 /var/www/AVideo/upload/objects/Streamer.php(26): mysqli->query()
#1 /var/www/AVideo/upload/objects/Streamer.php(68): Streamer::get()
#2 /var/www/AVideo/upload/objects/Login.php(108): Streamer::createIfNotExists()
#3 /var/www/AVideo/upload/objects/login.json.php(15): Login::run()
#4 {main}
  thrown in /var/www/AVideo/upload/objects/Streamer.php on line 26
```

The MySQL server log :

```
2023-12-30T01:33:12.614520Z 777 [ERROR] [MY-013183] [InnoDB] Assertion failure: pars0pars.cc:733:sym_node->table != nullptr thread 140279874106944
InnoDB: We intentionally generate a memory trap.
InnoDB: Submit a detailed bug report to http://bugs.mysql.com.
InnoDB: If you get repeated assertion failures or crashes, even
InnoDB: immediately after the mysqld startup, there may be
InnoDB: corruption in the InnoDB tablespace. Please refer to
InnoDB: http://dev.mysql.com/doc/refman/8.0/en/forcing-innodb-recovery.html
InnoDB: about forcing recovery.
2023-12-30T01:33:12Z UTC - mysqld got signal 6 ;
Most likely, you have hit a bug, but this error can also be caused by malfunctioning hardware.
BuildID[sha1]=73915b0bb061f1c7958738d6bcc1903b5a2e0aac
Thread pointer: 0x7f9508029400
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 7f957410ac40 thread_stack 0x100000
```

what is that :-(

**Comment by DanielnetoDotCom** [comment]
Looks like a corrupted table. I have no idea how to recover. 

but if the issue is with the encoder, you should just reinstall it from scratch.

**Comment by s-maisch** [comment]
I completely reinstalled the encoder. Can I also reinstall the site and use the data from the existing database so that I can take over video files etc.

**Comment by s-maisch** [comment]
I found the error, there was a user table in the main database. I downloaded the entire database as SQL. repaired the user table, changed the database name and imported it again. I then changed the database to the new one in the configuration file.

**Comment by PrXenon** [comment]
hmm i have the same problem... 
Encoder 4.0
VideoHLS 10.2

![image](https://github.com/WWBN/AVideo-Encoder/assets/3627520/f414c87d-9a24-43cf-addf-d06cbd564e28)

/Encoder/view/status.php

`{"queue_size":1,"concurrent":1,"is_encoding":false,"queue_list":[{"id":"195","name":"HLS","code":"-c:v h264 -vf scale=-2:{$resolution} -r 24 -g 48 -keyint_min 48 -sc_threshold 0 -bf 3 -b_strategy 2 -minrate {$minrate}k -crf 23 -maxrate {$maxrate}k -bufsize {$bufsize}k -c:a aac -b:a {$autioBitrate}k -f hls -hls_time 6 -hls_list_size 0 -hls_key_info_file {$destinationFile}keyinfo {$destinationFile}res{$resolution}\/index.m3u8","created":"2024-02-18 14:24:17","modified":"2024-02-18 14:24:17","extension":"m3u8","extension_from":"mp4","order":"6","fileURI":"https:\/\/url.de\/Encoder\/videos\/original_Video1_YPTuniqid_65d21310f3b6d2.52863896","filename":"Video1_YPTuniqid_65d21310f3b6d2.52863896","status":"queue","status_obs":"","return_vars":{"videos_id":1183,"video_id_hash":"a2syYjQvTE9UdllmYlkyUU1xSFB1ZHdZWlhHV0dmOW9kVk5IVldBQmJFQT0=","releaseDate":"2024-02-18 15:21:00"},"priority":"1","title":"Video1","videoDownloadedLink":"","downloadedFileName":"","streamers_id":"1","formats_id":"30","worker_pid":"0","worker_ppid":"0","streamer_site":"https:\/\/url.de\/","streamer_priority":"1"}],"msg":"We send the file to encode","encoding":[],"cmd":"","encoding_status":[],"version":"4.0","downloaded":[],"transferring":[]}`

/Encoder/view/run.php finished the queue and says:
`{"error":true,"hasNext":false,"msg":"There is no file on queue"}`

And the video appears here but its not completed
![image](https://github.com/WWBN/AVideo-Encoder/assets/3627520/daba7493-f03e-4462-9725-246b2d8d76f5)

I Updated the Encode 2 weeks ago.. all fine before.

Thanks
